name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent" \
          --health-interval=10s \
          --health-timeout=5s \
          --health-retries=3
    env:
      DJANGO_SETTINGS_MODULE: messaging_app.settings
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
      MYSQL_DATABASE: test_db
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r messaging_app/requirements.txt
          pip install flake8 coverage pytest pytest-cov
      - name: Run flake8 lint
        run: |
          flake8 messaging_app --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 messaging_app --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Fail on flake8 lint errors
        run: |
          flake8 messaging_app --count --select=E9,F63,F7,F82 --show-source --statistics --exit-zero
          if [ $? -ne 0 ]; then exit 1; fi
      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h 127.0.0.1 -u$MYSQL_USER -p$MYSQL_PASSWORD --silent; do
            sleep 2
          done
      - name: Run Django migrations
        run: |
          cd messaging_app
          python manage.py migrate
      - name: Run tests with coverage
        run: |
          cd messaging_app
          coverage run -m pytest || coverage run manage.py test
          coverage xml
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: messaging_app/coverage.xml
